name: Deploy WordPress

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY1 }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER1 }}@${{ secrets.EC2_HOST1 }} 'bash -s' << 'EOF'
            # Update system packages
            sudo apt-get update && sudo apt-get upgrade -y

            # Install necessary software
            sudo apt install -y git apache2 mysql-server php libapache2-mod-php php-gd php-mbstring php-xml php-zip php-curl
            systemctl status apache2 --no-pager -l
                      

            # Install Composer
            curl -sS https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
            sudo chmod +x /usr/local/bin/composer
            composer -v

            # Clone and set up Laravel project
            cd /var/www
            sudo git clone https://github.com/laravel/laravel.git
            cd /var/www/laravel
            sudo composer install
            sudo chown -R www-data:www-data /var/www/laravel
            sudo chmod -R 755 /var/www/laravel
            sudo chmod -R 777 /var/www/laravel/storage
            sudo cp .env.example .env
            php artisan key:generate

            # Update Apache configuration
            sudo nano /etc/apache2/sites-enabled/000-default.conf
             <VirtualHost *:80>
                ServerAdmin webmaster@localhost
                DocumentRoot /var/www/laravel/public

                <Directory />
                    Options FollowSymLinks
                    AllowOverride None
                </Directory>
                <Directory /var/www/laravel>
                    AllowOverride All
                </Directory>

                ErrorLog \${APACHE_LOG_DIR}/error.log
                CustomLog \${APACHE_LOG_DIR}/access.log combined
            </VirtualHost>
            EOF
            sudo a2ensite laravel.conf
            sudo a2enmod rewrite
            sudo systemctl restart apache2
          EOF
           
